Handle network errors better
1. Process network error instead of response
2. Error message on redirect loop
3. In both of the above call handler to avoid Loading Album message being stuck.

Received the following error when coverart was temp unavail:

D: 09:25:27 GET http://archive.org:80/download/mbid-8028cf3c-fcf5-4915-ae47-ca29b2875d64/index.json
    Traceback (most recent call last):
    File ".\picard\webservice.py", line 240, in _process_reply
    cached
    File ".\picard\log.py", line 81, in debug
    main_logger.message(LOG_DEBUG, message, *args)
    File ".\picard\log.py", line 58, in message
    message = message % args
TypeError: %d format: a number is required, not NoneType