Fix setFocus() in EditableListView
How to reproduce:
- in Options > Interface > Top Tags, press button Add new tag

Traceback (most recent call last):
  File "/home/zas/src/picard/./picard/ui/widgets/editablelistview.py", line 87, in add_empty_row
    self.setFocus(True)
TypeError: arguments did not match any overloaded call:
  setFocus(self): too many arguments
  setFocus(self, reason: Qt.FocusReason): argument 1 has unexpected type 'bool'


Solution:

Call with QtCore.Qt.FocusReason.OtherFocusReason instead of True