PICARD-603: fix missing imports
Traceback (most recent call last):
File "/usr/lib/picard/picard/ui/mainwindow.py", line 302, in _on_submit
self.tagger.acoustidmanager.submit()
File "/usr/lib/picard/picard/acoustidmanager.py", line 78, in submit
log.debug("AcoustID: submitting ...")
NameError: global name 'log' is not defined


and pylint tells more:

Module picard.ui.infodialog
E: 55,16: Undefined variable 'log' (undefined-variable)
E: 55,26: Undefined variable 'traceback' (undefined-variable)