Fix exception introduced in d765211120fe0 (#2638)
```
  File "picard/ui/metadatabox/edittagdialog.py", line 222, in _get_supported_tags
    tags = sorted(list(tag_names()) + self.metadata_box.tag_diff.tag_names)
                  ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'set' and 'list'
```

This issue was introduced in commit d765211120fe04429c2081b20c5b988d0b42e0d7, it should have been `list()` instead of `set()`, tag names are already unique, but `tag_names()` is a generator.