Only output CD read failure traceback in debug mode
It makes the log cleaner, as most of times CD read error is due to CD not inserted.

Without debug mode, output looks like:

```
E: 16:58:00 Error while reading b'/dev/sr1': cannot open device `/dev/sr1'
```

With debug mode:

```
D: 16:58:17 Reading CD using device: b'/dev/sr1'
E: 16:58:17 Error while reading b'/dev/sr1': cannot open device `/dev/sr1'
E: 16:58:17 Traceback (most recent call last):
  File "./picard/util/thread.py", line 47, in run
    result = self.func()
  File "./picard/disc.py", line 55, in read
    raise e
  File "./picard/disc.py", line 50, in read
    disc = discid.read(device)
  File "/home/zas/.virtualenvs/picard2/lib/python3.5/site-packages/discid/disc.py", line 55, in read
    disc.read(device, features)
  File "/home/zas/.virtualenvs/picard2/lib/python3.5/site-packages/discid/disc.py", line 152, in read
    raise DiscError(self._get_error_msg())
discid.disc.DiscError: cannot open device `/dev/sr1'
```