Fix a TypeError, str vs unicode.
E: 139836956702464 21:25:09 Traceback (most recent call last):
  File "./picard/album.py", line 133, in _parse_release
    run_album_metadata_processors(self, m, release_node)
  File "./picard/metadata.py", line 334, in run_album_metadata_processors
    processor(tagger, metadata, release)
  File "./picard/coverart.py", line 178, in coverart
    config.setting["caa_image_types"].split())
TypeError: descriptor 'lower' requires a 'unicode' object but received a 'str'