Remove unneeded toBool() forgotten in commit 6ff1f5350
Traceback (most recent call last):
  File "./picard/acoustid.py", line 219, in _on_fpcalc_error
    finished = process.property('picard_finished').toBool()
AttributeError: 'bool' object has no attribute 'toBool'