Fix AttributeError: 'ScriptEditorDialog' object has no attribute 'unsaved_changes_confirmation'
Traceback (most recent call last):
  File "/home/zas/src/picard/./picard/ui/mainwindow/__init__.py", line 300, in closeEvent
    if not self.script_editor_dialog.unsaved_changes_confirmation():
AttributeError: 'ScriptEditorDialog' object has no attribute 'unsaved_changes_confirmation'. Did you mean: 'unsaved_changes_in_profile_confirmation'?

This issue was introduced in e253ef4956fc6150be278613a515bce4619b6290