Prevent AttributeError when there is no "release_type_scores" option
It may happen during config option upgrade:
picard.config.ConfigUpgradeError: Error during config upgrade from version 1.3.0dev3 to 1.3.0dev4 using upgrade_to_v1_3_0_dev_4():
Traceback (most recent call last):
  File "./picard/config.py", line 141, in run_upgrade_hooks
    hook['func'](*hook['args'])
  File "./picard/config_upgrade.py", line 137, in upgrade_to_v1_3_0_dev_4
    _s[opt] = load_release_type_scores(_s.raw_value(opt))
  File "./picard/config_upgrade.py", line 126, in load_release_type_scores
    values = setting.split()
AttributeError: 'NoneType' object has no attribute 'split'

Reported in http://tickets.musicbrainz.org/browse/PICARD-592