Fix AttributeError: 'MetadataBox' object has no attribute 'shrink_columns'
shrink_columns() was replaced by resize_columns() in commit 4c64a277cdafd9906a7eb2d7c586383a335a3978