PICARD-602: import missing log
Traceback (most recent call last):
File "/usr/lib/picard/picard/webservice.py", line 241, in _process_reply
handler(str(reply.readAll()), reply, error)
File "/usr/lib/picard/picard/collection.py", line 102, in request_finished
echo=log.error
NameError: global name 'log' is not defined