Fix plugin install code
Fix following errors:

1. On plugin install:
Traceback (most recent call last):
File ".\picard\ui\options\plugins.py", line 133, in open_plugins
self.install_plugin(path)
File ".\picard\ui\options\plugins.py", line 138, in install_plugin
dest = os.path.join(self.tagger.user_plugin_dir, file)
AttributeError: 'Tagger' object has no attribute 'user_plugin_dir'

2. On Open Plugin Folder:
Traceback (most recent call last):
File ".\picard\ui\options\plugins.py", line 151, in open_plugin_dir
QtGui.QDesktopServices.openUrl(QtCore.QUrl(self.loader %
self.tagger.user_plugin_dir, QtCore.QUrl.TolerantMode))
AttributeError: 'Tagger' object has no attribute 'user_plugin_dir'.

Code missed from commit 7c4fdf765cd404ba0742f2513d039a5b69e8a71d on
2013-06-08.